from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
    path('', views.index, name='index'),
    path('trending/', views.trending, name='trending'),
    path('questions/', views.questions, name='questions'),
    path('superuser/', views.superuser_dashboard, name='superuser_dashboard'),
    path('questions/ask/', views.ask_question, name='ask_question'),
    path('search/suggestions/', views.search_suggestions, name='search_suggestions'),
    path('search/', views.search, name='search'),
    path('admin/post/<int:post_id>/votes/', views.adjust_post_votes, name='adjust_post_votes'),
    path('admin/comment/<int:comment_id>/votes/', views.adjust_comment_votes, name='adjust_comment_votes'),
    path('comment/<int:comment_id>/delete/', views.delete_comment, name='delete_comment'),
    path('d/<path:name>/<int:post_id>/', views.post_detail, name='post_detail'),
    path('d/<path:name>/<int:post_id>/delete/', views.delete_post, name='delete_post'),
    path('d/<path:name>/<int:post_id>/comment/', views.post_comment, name='post_comment'),
    path('d/<path:name>/<int:post_id>/solution/', views.update_question_solution, name='update_question_solution'),
    path('vote/post/<int:post_id>/', views.vote, name='vote_post'),
    path('vote/comment/<int:comment_id>/', views.vote, name='vote_comment'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup_view, name='signup'),
    path('profile/', views.profile_redirect, name='profile'),
    path('profile/photo/', views.update_profile_photo, name='update_profile_photo'),
    path('profile/bio/', views.update_profile_bio, name='update_profile_bio'),
    path('u/<str:username>/photo/', views.user_profile_photo, name='user_profile_photo'),
    path('u/<str:username>/hover-card/', views.user_hover_card, name='user_hover_card'),
    path('u/<str:username>/', views.profile_view, name='user_profile'),
    path('display-mode/', views.update_display_mode, name='update_display_mode'),
    path('notifications/read/', views.mark_notifications_read, name='mark_notifications_read'),
    path('create-subthread/', views.create_subthread, name='create_subthread'),
    path('d/<path:name>/join/', views.join_subthread, name='join_subthread'),
    path('d/<path:name>/leave/', views.leave_subthread, name='leave_subthread'),
    path('d/<path:name>/delete/', views.delete_subthread, name='delete_subthread'),
    path('d/<path:name>/create-post/', views.create_post, name='create_post'),
    path('d/<path:name>/', views.subthread_detail, name='subthread_detail'),
]
