# Generated by Django 6.0.1 on 2026-04-04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_subthread_memberships(apps, schema_editor):
    Subthread = apps.get_model("main", "Subthread")
    SubthreadMembership = apps.get_model("main", "SubthreadMembership")

    for subthread in Subthread.objects.all().iterator():
        SubthreadMembership.objects.get_or_create(
            user_id=subthread.created_by_id,
            subthread_id=subthread.id,
        )

    for subthread in Subthread.objects.all().iterator():
        subthread.members = SubthreadMembership.objects.filter(subthread_id=subthread.id).count()
        subthread.save(update_fields=["members"])


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0004_vote_constraints_cleanup"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubthreadMembership",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subthread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="main.subthread",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subthread_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="subthreadmembership",
            constraint=models.UniqueConstraint(
                fields=("user", "subthread"),
                name="unique_subthread_membership",
            ),
        ),
        migrations.RunPython(backfill_subthread_memberships, migrations.RunPython.noop),
    ]
