# Generated by Django 6.0.1 on 2026-04-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_question",
            field=models.BooleanField(default=False),
        ),
    ]
